baseurl: "https://thoughtF20.classes.ryansafner.com/"
languageCode: "en-us"
title: "History of Economic Thought"
theme: "ath-tufte-hugo_18-19"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Assignments
      url: /assignments/
      weight: 3
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Reference
      url: /reference/
      weight: 4
    - name: Slack
      url: "https://hoodcollegeeconomics.slack.com"
      weight: 6
# Disable taxonomies
taxonomies:
  tag: ""
  group: ""
  category: ""
params:
  author: Ryan Safner
  thumbnail: /images/thought_hex.png
  instructor: 
    name: Dr. Ryan Safner
    email: safner@hood.edu
    url: "https://www.ryansafner.com"
    twitter: ryansafner
    github: ryansafner
    office: 118 Rosenstock
  course:
    number: ECON 452
    semester: Fall 2020
    days: "MW"
    time: "3:25–4:45PM"
    location: "Meets on Zoom"
    twitter: ryansafner
    dates: >-
      August 17–November 24, 2020
    github: "ryansafner/thoughtF20"
    #slack: "https://hood-io.slack.com/"
    copyrightYear: "2020"
    contactDetails: >-
      Office hours: MW 3:15–5:00PM
  university: 
    name: Hood College
    url: "https://www.hood.edu"
  school:
    name: George B. Delaplaine, Jr. School of Business
    url: "https://www.hood.edu/academics/departments/george-b-delaplaine-jr-school-business"
  description: "History of Economic Thought"
  primaryColor: "#5E81AC"
  secondaryColor: "#D08770"
  credits: >-
    Hex icon by Ryan Safner via [hexSticker](https://github.com/GuangchuangYu/hexSticker).<br> Course website based on [Andrew Heiss](https://econw19.classes.andrewheiss.com/). <br>[Nord color scheme](https://github.com/arcticicestudio/nord) from [Arctic Ice Studio](http://arcticicestudio.com/).
  logo:
    url: /images/thought_hex.png
    alt: History of Economic Thought
  meta:
    twitterSite: "@ryansafner"
    twitterCreator: "@ryansafner"
    fbAuthor: "https://www.facebook.com/ryansafner"
